export enum Country {
    "United Kingdom",
    "Austria",
    "Belgium",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Latvia",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Netherlands",
    "Norway",
    "Romania",
    "Russian Federation",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "South Africa",
    "China (PR)",
    "Hong Kong (China)",
    "India",
    "Indonesia",
    "Japan",
    "Korea (Republic)",
    "Singapore",
    "Thailand",
    "Australia",
    "New Zealand",
    "Saudi Arabia",
    "Turkey",
    "United Arab Emirates",
    "Canada",
    "Mexico",
    "United States",
    "Argentina",
    "Brazil",
}