export const LOCATIONS = [
    { country: "United Kingdom", value: 212.3 },
    { country: "Austria", value: 111.2 },
    { country: "Belgium", value: 161.9 },
    { country: "Bulgaria", value: 372.1 },
    { country: "Croatia", value: 227 },
    { country: "Cyprus", value: 643 },
    { country: "Czech Republic", value: 495.5 },
    { country: "Denmark", value: 142.5 },
    { country: "Estonia", value: 598.7 },
    { country: "Finland", value: 95.3 },
    { country: "France", value: 51.3 },
    { country: "Germany", value: 338.7 },
    { country: "Greece", value: 410 },
    { country: "Hungary", value: 243.8 },
    { country: "Iceland", value: 0.1 },
    { country: "Ireland", value: 356 },
    { country: "Italy", value: 323.8 },
    { country: "Latvia", value: 215.7 },
    { country: "Lithuania", value: 253.6 },
    { country: "Luxembourg", value: 101.4 },
    { country: "Malta", value: 390.6 },
    { country: "Netherlands", value: 374.3 },
    { country: "Norway", value: 7.6 },
    { country: "Romania", value: 261.8 },
    { country: "Russian Federation", value: 310.2 },
    { country: "Serbia", value: 776.7 },
    { country: "Slovakia", value: 155.5 },
    { country: "Slovenia", value: 224.1 },
    { country: "Spain", value: 171 },
    { country: "Sweden", value: 5.7 },
    { country: "Switzerland", value: 11.5 },
    { country: "South Africa", value: 900.6 },
    { country: "China (PR)", value: 537.4 },
    { country: "Hong Kong (China)", value: 680 },
    { country: "India", value: 708.2 },
    { country: "Indonesia", value: 717.8 },
    { country: "Japan", value: 465.8 },
    { country: "Korea (Republic)", value: 415.6 },
    { country: "Singapore", value: 408 },
    { country: "Thailand", value: 442 },
    { country: "Australia", value: 760 },
    { country: "New Zealand", value: 101.4 },
    { country: "Saudi Arabia", value: 505.9 },
    { country: "Turkey", value: 375 },
    { country: "United Arab Emirates", value: 404.1 },
    { country: "Canada", value: 120 },
    { country: "Mexico", value: 431.4 },
    { country: "United States", value: 423.9 },
    { country: "Argentina", value: 307 },
    { country: " Brazil", value: 61.7 },
] 