import { Country } from "./country";

export const LOCATIONS = [
    { country: Country["United Kingdom"], value: 212.3 },
    { country: Country["Austria"], value: 111.2 },
    { country: Country["Belgium"], value: 161.9 },
    { country: Country["Bulgaria"], value: 372.1 },
    { country: Country["Croatia"], value: 227 },
    { country: Country["Cyprus"], value: 643 },
    { country: Country["Czech Republic"], value: 495.5 },
    { country: Country["Denmark"], value: 142.5 },
    { country: Country["Estonia"], value: 598.7 },
    { country: Country["Finland"], value: 95.3 },
    { country: Country["France"], value: 51.3 },
    { country: Country["Germany"], value: 338.7 },
    { country: Country["Greece"], value: 410 },
    { country: Country["Hungary"], value: 243.8 },
    { country: Country["Iceland"], value: 0.1 },
    { country: Country["Ireland"], value: 356 },
    { country: Country["Italy"], value: 323.8 },
    { country: Country["Latvia"], value: 215.7 },
    { country: Country["Lithuania"], value: 253.6 },
    { country: Country["Luxembourg"], value: 101.4 },
    { country: Country["Malta"], value: 390.6 },
    { country: Country["Netherlands"], value: 374.3 },
    { country: Country["Norway"], value: 7.6 },
    { country: Country["Romania"], value: 261.8 },
    { country: Country["Russian Federation"], value: 310.2 },
    { country: Country["Serbia"], value: 776.7 },
    { country: Country["Slovakia"], value: 155.5 },
    { country: Country["Slovenia"], value: 224.1 },
    { country: Country["Spain"], value: 171 },
    { country: Country["Sweden"], value: 5.7 },
    { country: Country["Switzerland"], value: 11.5 },
    { country: Country["South Africa"], value: 900.6 },
    { country: Country["China (PR)"], value: 537.4 },
    { country: Country["Hong Kong (China)"], value: 680 },
    { country: Country["India"], value: 708.2 },
    { country: Country["Indonesia"], value: 717.8 },
    { country: Country["Japan"], value: 465.8 },
    { country: Country["Korea (Republic)"], value: 415.6 },
    { country: Country["Singapore"], value: 408 },
    { country: Country["Thailand"], value: 442 },
    { country: Country["Australia"], value: 760 },
    { country: Country["New Zealand"], value: 101.4 },
    { country: Country["Saudi Arabia"], value: 505.9 },
    { country: Country["Turkey"], value: 375 },
    { country: Country["United Arab Emirates"], value: 404.1 },
    { country: Country["Canada"], value: 120 },
    { country: Country["Mexico"], value: 431.4 },
    { country: Country["United States"], value: 423.9 },
    { country: Country["Argentina"], value: 307 },
    { country: Country["Brazil"], value: 61.7 },
] 