name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install
        run: npm install

      - name: run lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: run test
        run: npm run test